version: '3.7'

services:
  web:
    build:
      context: ./app
      dockerfile: Dockerfile.semi.prod
    command: bash -c "daphne -b 0.0.0.0 -p 8000 bayatStream.asgi:application
    image: "bayatStream:latest"
    volumes:
      - static_volume:/home/app/web/staticfiles
      - media_volume:/home/app/web/mediafiles
    expose:
      - 8000
    env_file:
      - ./.env.prod
    depends_on:
      - db
  worker:
    image: "bayatStream:latest"
    working_dir: /home/app/web
    command: bash -c "python manage.py runworker"
    env_file:
      - ./.env.prod
    depends_on:
      - redis
  redis:
    image: redis:latest
    ports:
      - "6379:6379"
  db:
    image: postgres:12.0-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./.env.prod.db
  nginx:
    build: ./nginx
    volumes:
      - static_volume:/home/app/web/staticfiles
      - media_volume:/home/app/web/mediafiles
    environment:
      - NGINX_PORT=80
      - DAPHNE_HOST=daphne
      - DAPHEN_PORT=8000
    ports:
      - 80:80
    depends_on:
      - web
      - worker
volumes:
  postgres_data:
  static_volume:
  media_volume:
